
mysqli:
	sed -i  s/mysql_fetch_array/mysqli_fetch_array/  *.php

mysqli_query:
	sed -i 's/mysql_query(/mysqli_query($connection /'  start.php

mysqli_fetch_row:
	sed -i 's/mysql_fetch_row/mysqli_fetch_row/'  *.php


mysqli_error:
	sed -i 's/mysql_error/mysqli_error/'  *.php

mysqli_close:
	sed -i 's/mysql_close/mysqli_close/'  *.php

mysqli_num_rows:
	sed -i 's/mysql_num_rows/mysqli_num_rows/'  *.php
