#/usr/bin/perl -w
 
use DBI;
use Mail::Mailer;
 
 
# setz alle bei denen keinn mail vorhanden die main_generation zu null
# auch alle die einen anderen status als 7 = online haben
#schreibt mail , dass jetzt 10 clones vorhanden sind 
connect_db();
 
 
 
sub connect_db{
    my $server = "localhost";
    my $db = "tracenoizer";
    $dbh = DBI->connect ("DBI:mysql:$db:$server",'web','w2kkadb');
    if (not $dbh){
        print "----> no connection to the db";
    }
    print "----> connection to db $db established \n";
}
 
 
 
 
$select = $dbh->prepare("select main_usr_id from main where main_generation = 11 and  main_id > 27655" );
$select->execute;
my $usr_id  = $select->fetchrow_array;
push (@usr_id,$usr_id);

while ($usr_id != undef){
    $usr_id= $select->fetchrow_array;
    push (@usr_id,$usr_id);
}
 
 
 
 
for (my $k=0 ;$k < @usr_id;$k++){
    $select = $dbh->prepare("select usr_name,usr_pw,usr_mail from users where usr_id = '$usr_id[$k]'");
    $select->execute;
    my ($usr_name,$usr_pw,$usr_mail)  = $select->fetchrow_array;  
    print $usr_id[$k]." ".$usr_name." ". $usr_pw." ". $usr_mail."\n"; 
    if (length($usr_mail) > 1 ){
	my $body = "hi $usr_name\n\n";
	$body = $body . "tracenoizer.org has generated 10 clones of your databody:\n\n";
	$select = $dbh->prepare("select main_weblink from main where main_usr_id = '$usr_id[$k]'");
	$select->execute;
	$weblink  = $select->fetchrow_array;
	my @weblink= ();
	push (@weblink,$weblink);
	for (my $r=0 ;$r < 10;$r++){ 
	    $weblink= $select->fetchrow_array;
	    push (@weblink,$weblink);     
	}
	for(@weblink){
	    $body = $body . "$_\n";
	    #print $_."\n";
	    
	}
	$body = $body . "\n\nto watch your clone, login with your ";  
	$body = $body . "username: $usr_name and \nyour password ";                       
	$body = $body . "at http://www.tracenoizer.org \nor use the link below:\n\n";                       
	$body = $body . "http://www.tracenoizer.org/control.php?usr=".$usr_name."\n\n";
	$body = $body . "you can delete your clones by using the \n'permanently kill this clone' button.\n\n\n";
	$body = $body . "------------------ http://www.tracenoizer.org ---------------\n";
	$body = $body . "------------------- Desinformation On Demand ----------------\n";  
	print $body;
	$subject = "your 10 clones generated by tracenoizer.org";
	mailsend($subject,$body,$usr_mail);
	$body = $body . "------------------- mail an $usr_mail ----------------\n";      
	$usr_mail = "martin\@krungkuene.org";
	
	mailsend($subject,$body,$usr_mail);    
	$usr_mail = undef;   
    }
}


sub mailsend {
    my $subject = $_[0];
    my $body = $_[1];
    $to_address = $_[2];
    $from_address = "tracenoizer\@krungkuene.org";
    $mailer = Mail::Mailer->new("sendmail");
    $mailer->open({ From    => $from_address,
		    To      => $to_address,
		    Subject => $subject
		    })
        or die "Can't open: $!\n";
    print $mailer $body;
    $mailer->close();
}

$select = $dbh->prepare("update main set main_generation = 12 where main_generation = 11");
$select->execute;     







